### ISSUE TITLE
SSL Wrong version number

### ISSUE THREAD

**Issue by gjongenelen** [simllll/node-radius-server#2]
Hi there,

First, thank you for your great work.

I tried out your lib in my auth-server project, but face a problem while using it on WPA2-enterprise. 
The following error occurs: _140529911364936:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332_
Note: this is when I build in docker, using the node:10-alpine image

When running locally on my mac I get the following error: _4520836544:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_srvr.c:643_ 

I'm not really into SSL, so maybe you can clarify some things? (Debugging didn't help me, I got stuck at crypt.ts)

**Comment by simllll** [comment]
Unsure about the wrong version number issue, but you need for sure a special node version.

See my comment in the readme

> This is a first implementation draft, which is currently only working with a nodejs fork (see https://github.com/nodejs/node/pull/31814).

As long this is not merged into the master, you need to build your own nodejs version.

**Comment by gjongenelen** [comment]
Thanks, missed that comment.

**Comment by simllll** [comment]
@gjongenelen I found the issue, it was related to some missing code implementations ;) in your case I believe it had to do with the "Length" bit.. just commited the new version.
ensure that you rebuild your certificate, as it turned out that there was also something missing. it works now with windows clients too :)
