### ISSUE TITLE
invalid username, not found in DN

### ISSUE THREAD

**Issue by coozgan** [simllll/node-radius-server#336]
Hi I have problem with authenticating the Google LDAP

I have followed the step in setting up client for LDAP but I couldn't get myself authenticated with the app. I have tried every settings in my google admin console but it still wont' authenticate me.

**My Google Admin Console LDAP setup like this**
> **Verify user credentials**
> _Selected organizational units, groups and excluded groups (For my specified OU)_
> 
> **Read user information**
> _Selected organizational units, groups and excluded groups (For my specified OU)_
> 
> **System Attributes** - Checked
> **Read group information** - Checked

And the **status are ON**

I have uploaded and rename the certificates and key in the root level directory of config file.

I'm so sorry for being completely noob I am just not sure how should i move forward with this.
any help is appreciated. Thanks!

**Comment by avicoder** [comment]
Can you share the output logs after you start the server.

**Comment by coozgan** [comment]
It's my bad I I left this life as it is;
```
var config = {
	// ....
	authentication: 'GoogleLDAPAuth',
	authenticationOptions: {
		base: 'dc=hokify,dc=com'
	}
};
```
Base should be our own domain.
Thanks!
